### ISSUE TITLE
KB-25101 / Trac-7234 visornic faults after IOVM sp recovery with visornic NAPI changes (visornic upstream)

### ISSUE THREAD

**Issue by ghost** [davidker/unisys#106]
[KanBoard-25101](http://ustr-erl-6690.na.uis.unisys.com/?controller=task&action=show&task_id=25101&project_id=37) / [Trac-7234](https://ustr-svn-1.na.uis.unisys.com/trac/spar/ticket/7234)

**Comment by ghost** [comment]
**Branch:** githubissue-106-for-later-TurningWrenches
**Commit(s):** 
8e0579cf24f106f82a97cd1d0c75f5c81943bc98
886922a0a811bd16c394572eed72b9de3ed72cd6
00bd18ce286d4edd7e568eb12b16b2bb2fe3e97f
5561dc1f025290de70bead7ad9281e506df02982
678af8e9cdf95993a9c5244117deaae0e23c1fa0
74b099ee99ca8b1a8368222b60813337cc36732d
2cf63edc44e8b2c467edb41e75ea0727462254f4
4c29fffef8ad3e4bda197ce3fbc9032989a3d501
**checkpatch-cleared:** Yes
**T710-1 verified:** No

**Comment by selltc** [comment]
I successfully verified David's fix for this on my T110 as described [in comment-23 of Trac-7234](https://ustr-svn-1.na.uis.unisys.com/trac/spar/ticket/7234#comment:23), but I also needed commit b1359d11b381ce4aedae021eb5154425872fe64a (remove unnecessary declaration of visorbus_free_irq()) in order to compile cleanly.

**Comment by ghost** [comment]
Please also add this commit: fc44a49d292a00284972f79b7c83d378727bf5f1 ( @davidker, @selltc).

**Comment by selltc** [comment]
As in #107, we also need to add commit 34801316e9131ad2ac05dde83e5ec1f8c179e2c4 (staging: unisys: remove redundant unlocks of visornic_devdata.priv_lock) here, in order to fix a problem introduced by commit 2cf63edc44e8b2c467edb41e75ea0727462254f4 (staging: unisys: visornic: Remove errant -EIO returns).

**Comment by davidker** [comment]
Fixed in forlater
