### ISSUE TITLE
Nits in initialize/destroy_controlvm_payload_info()

### ISSUE THREAD

**Issue by davidker** [davidker/unisys#124]
Task #24543

**Comment by davidker** [comment]
Realized they aren't actually being used just created and destroyed. So we can get rid of it. Patch is located on branch [githubissue-124-upstream-next](https://github.com/davidker/unisys/tree/githubissue-124-upstream-next) with the patch: 08a82575d406cb74e17ccfcd1a61923e9f2693ee.

**Comment by ghost** [comment]
So I understand what your patch is doing, and it looks fine to me. My only comment is to refine the commit message a bit more. When I read it, I don't make the connection that visor_controlvm_payload_info has anything to do with sending payloads back to the s-Par firmware. I might say something to the effect of "Removing visor_controlvm_payload_info structure, which was used to send payloads back to the s-Par firmware, because we do not implement that functionality."

**Comment by davidker** [comment]
Committed at d308d2b
